#!/usr/bin/python

import os, sys, dbus

bus = dbus.SystemBus()
object = bus.get_object('org.frugalware.UpdNotifier', '/org/frugalware/UpdNotifier')

if len(sys.argv) < 2: 
	print "Must specify an action: start, stop, changeprofile"
	sys.exit(1)

def doUpdateCheck():
	print "checking for updates..." ,
	ret = object.PerformUpdate()
	if ret == 0:
		print "success"
	else:
		print "failed"

if sys.argv[1] == "start":
	doUpdateCheck()
else:
	print "Invalid action. Valid actions are: start, stop, changeprofile"
	sys.exit(1)
