#!/usr/bin/python

import os, sys, dbus

if os.getuid() != 0:
	print "Must be run as root!"
	sys.exit(1)

bus = dbus.SystemBus()
object = bus.get_object('org.frugalware.NetConfig', '/org/frugalware/NetConfig')

if len(sys.argv) < 2: 
	print "Must specify an action: start, stop, changeprofile"
	sys.exit(1)

def doStop():
	print "Stopping networking... " ,
	ret = object.StopNetworking()
	if ret > 0:
		print "failed!"
	else:
		print "done."

def doStart():
	print "Starting networking... " ,
	ret = object.StartNetworking()
	if ret > 0:
		print "failed!"
	else:
		print "done."

def doChangeProfile(profile):
	print "Changing profile... " ,
	ret = object.ChangeProfile(profile)
	if ret > 0:
		print "failed!"
	else:
		print "done."

if sys.argv[1] == "stop":
	doStop()
elif sys.argv[1] == "start":
	doStart()
elif sys.argv[1] == "changeprofile":
	if len(sys.argv) != 3:
		doChangeProfile(sys.argv[2])
	else:
		print "Missing profile name!"
		sys.exit(1)
else:
	print "Invalid action. Valid actions are: start, stop, changeprofile"
	sys.exit(1)
